#!/usr/bin/python
import sys
import swsssdk
import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
logger.addHandler(logging.NullHandler())

if len(sys.argv) < 3:
    msg = "More than three arguments are required. 'usage: sonic-db-cli dbname rediscommands'"
    print >> sys.stderr, msg
    logger.error(msg)
else:
    dbname = sys.argv[1]
    dbconn = swsssdk.SonicV2Connector(use_unix_socket_path=False)
    try:
        dbconn.connect(dbname)
    except RuntimeError:
        msg = "Invalid database name input : '{}'".format(sys.argv[1])
        print >> sys.stderr, msg
        logger.error(msg)
    else:
        client = dbconn.get_redis_client(dbname)
        print client.execute_command(" ".join(sys.argv[2:]))
